CREATE TABLE `albums` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `text` TEXT DEFAULT NULL,
  `picture` VARCHAR(300) NOT NULL,
  `datum_vytvorenia` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


ALTER TABLE `albums`
    MODIFY COLUMN `text` VARCHAR(255) DEFAULT NULL;